//Exercise #1

When a Mule app starts, a connectivity test runs on components, such as the HTTP or FTP connector, that need to connect to an external server. If the test fails, the default behavior is to log a warning message and continue with the deployment of the app, instead of blocking the deployment. You can modify this behavior by:

* Setting a number of reconnection attempts to try after an initial failure.
* Forcing the deployment to fail when all connection attempts fail.

You can set these parameters to modify the behavior:

* Fails Deployment (`failsDeployment`): Forces the deployment to fail if the connection fails and any configured reconnection attempts are exhausted.
* Reconnect (`reconnect`): Limits the number of reconnection attempts and the interval at which to execute them. For example, you might set a count of 5 reconnection attempts at a `frequency` of every 4000 milliseconds (ms). By default, it attempts to reconnect twice at a frequency of 2000 ms.
* Reconnect Forever (`reconnect-forever`): Attempts to reconnect at a given interval. For example, it attempts to reconnect every 4000 ms for as long as the app runs. By default, it attempts to reconnect at an interval of every 2000 ms because there is no limit on the number of retries. No value for `count` is specified.

Example that fails after 5 reconnection attempts are exhausted:

[source,xml]
----
<http:request-config name="HTTP_Request_Config" doc:name="HTTP Request Config">
  <http:request-connection host="https://jsonplaceholder.typicode.com/posts" port="80">
    <reconnection failsDeployment="true">
      <reconnect frequency="4000" count="5"/>
    </reconnection>
  </http:request-connection>
</http:request-config>
----

Example that does not set a limit on the number of reconnection attempts:

[source,xml]
----
<http:request-connection host="https://jsonplaceholder.typicode.com/posts" port="80">
  <reconnection>
    <reconnect-forever frequency="4000" count=”5”/>
  </reconnection>
</http:request-connection>
----
